// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizzWeb.AppDbContext;

#nullable disable

namespace QuizzWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240723070626_fixdatabase")]
    partial class fixdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizzWeb.Model.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("RigtAnswer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "4",
                            QuestionId = 1,
                            RigtAnswer = false
                        },
                        new
                        {
                            Id = 2,
                            Content = "5",
                            QuestionId = 1,
                            RigtAnswer = true
                        },
                        new
                        {
                            Id = 3,
                            Content = "6",
                            QuestionId = 1,
                            RigtAnswer = false
                        },
                        new
                        {
                            Id = 4,
                            Content = "7",
                            QuestionId = 1,
                            RigtAnswer = false
                        },
                        new
                        {
                            Id = 5,
                            Content = "7",
                            QuestionId = 2,
                            RigtAnswer = false
                        },
                        new
                        {
                            Id = 6,
                            Content = "8",
                            QuestionId = 2,
                            RigtAnswer = false
                        },
                        new
                        {
                            Id = 7,
                            Content = "9",
                            QuestionId = 2,
                            RigtAnswer = true
                        },
                        new
                        {
                            Id = 8,
                            Content = "10",
                            QuestionId = 2,
                            RigtAnswer = false
                        });
                });

            modelBuilder.Entity("QuizzWeb.Model.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = " 2+3=?",
                            QuizId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "3*3=?",
                            QuizId = 1
                        });
                });

            modelBuilder.Entity("QuizzWeb.Model.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Math Questions"
                        });
                });

            modelBuilder.Entity("QuizzWeb.Model.Answer", b =>
                {
                    b.HasOne("QuizzWeb.Model.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizzWeb.Model.Question", b =>
                {
                    b.HasOne("QuizzWeb.Model.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizzWeb.Model.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("QuizzWeb.Model.Quiz", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
